### ISSUE TITLE
Does this library work with Brother HL-L5102DW?

### ISSUE THREAD

**Issue by davimateus1** [IvanStoilov/react-native-brother-printing#1]
Hello, i need to create an app with react native that prints to this printer mentioned in the title (Brother HL-L5102DW), does your library do this or do you have any ideas on how I can do it?

I tested your library but I was not successful in either case (printing and getting information from the connected printer)

**Comment by IvanStoilov** [comment]
Hey, the supported devices are PJ-763MFi, PJ-862, PJ-863, PJ-883, MW-145MFi, MW-260MFi, RJ-2050, RJ-2150, RJ-3050Ai, RJ-3150Ai, RJ-3230B, RJ-3250WB, RJ-4030Ai, RJ-4230B, RJ-4250WB, QL-820NWB, QL-820NWBc, QL-1110NWB, QL-1110NWBc, TD-2125NWB, TD-2135NWB, TD-4550DNWB, PT-P910BT, RJ-2035B, RJ-3035B.

You can find more info here - https://support.brother.com/g/s/es/dev/en/mobilesdk/download/index.html?c=eu_ot&lang=en&navi=offall&comple=on&redirect=on#iphone. This is the library that is used for printing. 
`react-native-brother-printing` is just a wrapper around it. 

For more SDK's check out this page - https://developerprogram.brother-usa.com/sdk-download#largepromo7

**Comment by davimateus1** [comment]
Can you tell me what I need to adapt to the model I mentioned above and also if this is possible?

**Comment by davimateus1** [comment]
Its technical sheet shows that it is compatible with Mac OS X, Windows 7, Windows 8, Windows XP, Linux, Windows 10. Is it possible to create this implementation with Android? Its model is HL L5202DW and connectivity is via USB and WiFi

**Comment by davimateus1** [comment]
From what I researched, I believe that it is not possible, nor does this model exist in Brother's SDK list, not to mention that the Android OS is not shown as compatible in the technical sheet of this printer.

**Comment by IvanStoilov** [comment]
Indeed, I think it's not possible.
